### ISSUE TITLE
gaomon s620

### ISSUE THREAD

**Issue by zekyuro** [AbdShullah/TabletDriver#1]
## Hardware/software information
Windows Version: 2004

Tablet Driver version:  0.1.5.5

Tablet model: gaomon s620

hey the drivers dont recognize gaomon s620

**Comment by AbdShullah** [comment]
@zekyuro 
This fork is now retired, please use [this](https://github.com/InfinityGhost/OpenTabletDriver)
It supports almost all tablets without additional software and it has devocub filter plugin.
