### ISSUE TITLE
Drivers not functioning on cth 690

### ISSUE THREAD

**Issue by shimakazevr** [AbdShullah/TabletDriver#2]
hi, driver is not currently working with the cth 690, i plugged in my ctl 480 and its working correctly so im assuming the 690 is just not supported?

## Hardware/software information
Windows Version: 20H2

Tablet Driver version: 1.5.5 devocub

Tablet model: cth 690

**Comment by AbdShullah** [comment]
yeah, you are correct but I think OpenTabletDriver supports cth690, so you can try it instead of this abandoned driver
